### PR TITLE
Address deprecations, get package working in latest version of Atom

### LINKED ISSUE #24: Atom.Object.defineProperty.get is deprecated.
The atom.syntax global is deprecated. Use atom.grammars instead.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:325:11)
SymbolIndex.processFile (/Users/spacebiker/.atom/packages/goto/lib/symbol-index.coffee:175:19)
```

### PR DESCRIPTION
**Pull request by acusti**
Fixes #24, #25, #26, #27, #28, #29, #30, #31, #32, #33, #34, #35, #36, #37, #38, #39, #40, #41, #42, #43, #44, #45, #46, #47, #48, #49 :smile:

### CODE REVIEW

**Comment by v3ss0n** [comment]
Very good , i am reviewing and merging it.

**Comment by v3ss0n** [comment]
Looks goood , merging and testing. !

**Comment by magalhas** [comment]
:+1:

**Comment by v3ss0n** [comment]
Publishing! Thanks a lot @acusti

**Pull request merged**
