### PR TITLE
Issue #65 - always use up-to-date GitRepo objects and project directories

### LINKED ISSUE #65: Uncaught Error: Repository has been destroyed
[Enter steps to reproduce below:]

Ctrl + Shift + R

**Atom Version**: 1.0.7
**System**: Ubuntu 14.04.3
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught Error: Repository has been destroyed

```
At /opt/atom/resources/app.asar/src/git-repository.js:382

Error: Repository has been destroyed
  at GitRepository.module.exports.GitRepository.getRepo (/opt/atom/resources/app.asar/src/git-repository.js:382:15)
  at GitRepository.module.exports.GitRepository.isPathIgnored (/opt/atom/resources/app.asar/src/git-repository.js:226:19)
  at SymbolIndex.module.exports.SymbolIndex.keepPath (/home/freon/.atom/packages/goto/lib/symbol-index.coffee:216:18)
  at SymbolIndex.module.exports.SymbolIndex.processDirectory (/home/freon/.atom/packages/goto/lib/symbol-index.coffee:169:11)
  at SymbolIndex.module.exports.SymbolIndex.rebuild (/home/freon/.atom/packages/goto/lib/symbol-index.coffee:117:8)
  at SymbolIndex.module.exports.SymbolIndex.update (/home/freon/.atom/packages/goto/lib/symbol-index.coffee:109:8)
  at SymbolIndex.module.exports.SymbolIndex.getAllSymbols (/home/freon/.atom/packages/goto/lib/symbol-index.coffee:100:6)
  at Object.module.exports.gotoProjectSymbol (/home/freon/.atom/packages/goto/lib/index.coffee:41:22)
  at atom-workspace.atom.commands.add.goto:project-symbol (/home/freon/.atom/packages/goto/lib/index.coffee:20:34)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:241:29)
  at /opt/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -1:56.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:48.9.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:48.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:45.9.0 core:paste (atom-text-editor.editor.is-focused)
     -1:40.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:37.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:37.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:36.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:29.6.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:26.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:26.1.0 core:delete (atom-text-editor.editor.mini.is-focused)
     -0:32.1.0 core:close (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:31.1.0 goto:file-symbol (atom-text-editor.editor.is-focused)
     -0:24.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:24.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:19.6.0 goto:project-symbol (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "jsformat",
      "atom-ctags",
      "duplicate-line-or-selection",
      "atom-ternjs",
      "autocomplete-hack"
    ],
    "projectHome": "/home/www",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "goto": {
    "moreIgnoredNames": "node_modules, *.sql, *.html, *.css, *.scss, *.rb, *.md, *.json"
  }
}
```
### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-beautify, v0.28.11
atomatigit, v1.5.4
autocomplete-paths, v1.0.2
color-picker, v2.0.11
ctrl-last-tab, v0.2.0
docblockr, v0.7.3
git-diff, v0.55.0
git-plus, v5.4.4
goto, v1.7.1
highlight-selected, v0.10.1
language-cmake, v0.1.4
language-cpp14, v0.3.0
language-diff, v0.3.1
language-docker, v1.1.3
language-ini, v1.11.0
linter, v1.4.3
local-history, v3.2.3
minimap, v4.12.3
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
pigments, v0.11.0
pretty-json, v0.4.1
project-manager, v1.15.11
svn, v0.0.8
tab-numbers, v0.3.0
tabs-to-spaces, v0.11.1
tidy-tabs, v0.2.0

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by mshenfield**
This fixes #65, which was caused by goto caching GitRepo instances
after they were destroyed.  This also makes sure that goto always
pulls the latest project directories.

Since we are no longer caching any repos, we could remove @roots,
@repos, and the getProjectRepositories method in favor of pure atom
apis.

### CODE REVIEW

**Comment by despairblue** [comment]
@v3ss0n are still maintaining this? If not it would be cool, if you could have a look at the PRs and ask those people If they want to take over.

**Comment by v3ss0n** [comment]
Anyone want to take over? I haven't been able to code for a few months , due to busy with expanding my startup team. Thanks.

**Comment by despairblue** [comment]
@acusti @ebayer @globegitter @mkleehammer Has anyone of you the time to review PRs from time to time and publish the package?

**Comment by mkleehammer** [comment]
I'm afraid I really can't anymore - I handed the project over.  Sorry.

**Comment by acusti** [comment]
I’ll give it a shot. Got swamped recently, but I’m emerging now.

**Comment by acusti** [comment]
⌛️…⌛️…⌛️…⌛️…⌛️…⌛️…⏳ :shipit:

**Pull request merged**
